---
title: "Intro GGplot"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
```

## Leyendo Datos

```{r cars}
data(mpg)
# View(mpg) #leyendo datos
attach(mpg)
str(mpg)
```

## Including Plots

```{r }
p <- ggplot(data = mpg) # PASO 1
p + geom_point(aes(x=displ,y=hwy))

# ?geom_point # Buscar Ayuda
```

>Tipos de Figuras:
<https://www.dropbox.com/s/h18nmf5vahdidzs/figuras.Rmd?dl=0>

## Aplicando aes

```{r }
    p + geom_point(aes(x=displ,y=hwy), shape=23, size=3, color="red",fill="yellow")

```
    
## Grafica en 3D

```{r 3d class}
p + geom_point(aes(x=displ,y=hwy, color=class),size=3)
```


```{r 3d-class}
p + geom_point(aes(x=displ,y=hwy, color=(displ <= 4) ), size=3)
```
## Caso 2

```{r}
#str(mtcars) # Nuevo Data Frame
    p <- ggplot(mtcars, aes(wt, mpg))
 
    p + geom_point(aes(colour = cyl), size=3) # No es un factor es número
```


```{r}
p + geom_point(aes(colour = factor(cyl)), size=3)
```


```{r}
p + geom_point(aes(shape = factor(cyl)), size=3)
```


```{r}
p + geom_point(aes(colour = factor(cyl)), size = 4) 
    
```



